### PR TITLE
Removing old docs and addressing build warnings.

### PR DESCRIPTION
**Pull request by eirikurj**
## Purpose
Remove docs duplication. This PR addresses issue #2 

## Type of change
- Documentation update

## Testing
Built locally

## Checklist
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by joanibal** [comment]
This is to address issue #2, Correct?

**Comment by eirikurj** [comment]
Yes, I did mention the issue in the PR "purpose", so it should show up and be tracked with the issue as well.

**Comment by joanibal** [comment]
lol, totally missed that.
I'll added at as linked issue too

Everything looks good to me

**Comment by anilyil** [comment]
Instead of removing the whole section, can't we just link to the "better" documentation? Maybe, we can also include the doi numbers for the overset paper etc.?

**Comment by eirikurj** [comment]
This particular section is a tutorial on how to use ICEM to generate CGNS meshes, which is unrelated to ADflow (with the exception that ADflow uses CGNS meshes).
To address your comment on adding a link, I improved the tutorial sections, by adding a link to the MACH aero tutorial.
Adding a DOI to the overset papers is also a good idea since it describes the implementation, but its not a tutorial. However, I dont think that it is relevant for the particular issue that his PR is addressing. Perhaps create a new issue which describes the improvements?

**Comment by anilyil** [comment]
This PR looks good to me. I agree on adding the doi stuff for the other relevant publications also. Lets discuss the format for adding all relevant doi numbers and we can work on adding them to the adflow docs.

**Pull request merged**
