### PR TITLE
fprettify

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

Formatting the Fortran code with fprettify

## Expected time until merged

1 week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

Current tests pass

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by sseraj** [comment]
fprettify is failing because of this issue https://github.com/pseewald/fprettify/issues/93
The issue has been fixed but is not available on the latest tag on pyPI.

**Comment by nwu63** [comment]
> fprettify is failing because of this issue [pseewald/fprettify#93](https://github.com/pseewald/fprettify/issues/93) The issue has been fixed but is not available on the latest tag on pyPI.

Do you wanna open an issue there to ask if they can make a new release?

**Comment by sseraj** [comment]
I am converting this PR into a draft until we merge another PR that removes label statements. Labels are not considered best practice for F90 and cause problems with fprettify.

**Comment by nwu63** [comment]
@sseraj are the labels changed in #228? I just don't want this to get too stale since this potentially blocks all Fortran development.

**Comment by sseraj** [comment]
The labels are not changed in #228. I will open another PR for the label fixes, but I have not had time to work on that lately. I will try to have the labels fixed by the time we merge #231, because we want to merge that PR before this one anyway.

**Comment by sseraj** [comment]
I don't know what's going on with the complex build because both of the last commits work for me locally. For context, I tried changing complexify.py to get it to stop replacing strings like "======" with ".ceq..ceq..ceq.". This was happening even before the fprettify changes but did not cause errors because the line character limit was not being exceeded. With the indenting changes in this PR, the line character limit is being exceeded.

**Comment by sseraj** [comment]
This is ready to be merged. @marcomangano @ArshSaja

The only Fortran file that has manual changes is `src/preprocessing/preprocessingAPI.F90`. The manual changes were necessary to fix the complex build issue that I mentioned above. I replaced the equal signs with dashes in the strings that were causing problems. Ideally, complexify.py would not change strings at all, but this would involve changes to the parser. I opened an issue for this in the complexify repo, which will eventually replace the current complex build process.

**Review by marcomangano — APPROVED** [review]
The manual changes are fine. Everything else is assumed fine as the tests pass without issue -  the git diff is not helpful unfortunately. Please add the commit hash to `.git-blame-ignore-revs` asap.
Nice job!

**Comment by sseraj** [comment]
Yes, I will open another PR updating `.git-blame-ignore-revs` after this is merged.

**Review by ArshSaja — APPROVED** [review]

**Pull request merged**
