### PR TITLE
Added an option to specify acceptable adjoint convergence

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

I added an option called `adjointMaxL2DeviationFactor` that allows the user to specify how much worse than the target convergence is acceptable for the adjoint solution. This works the same way as `maxL2DeviationFactor` but for the adjoint instead of the flow solution.

This is a more precise alternative to setting `skipAfterFailedAdjoint` to False. See #45 for some related discussion.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by sseraj** [comment]
> did the test fail randomly again?

Yes, it did. I'll rerun the tests for this PR and also try to prioritize fixing the memory issue. It seems like the failures are showing up more frequently now somehow, possibly due to changes on the Azure runners.

**Comment by nwu63** [comment]
Why did codecov not work here? The logs say 
```
Error POSTing to https://codecov.io: 500 {"error": "Server Error (500)"}
There was an error running the uploader: Error uploading to https://codecov.io: Error: Internal Server Error
```

**Comment by sseraj** [comment]
> Why did codecov not work here?

PRs from forks (no token) still run into this issue but there is an open PR on codecov to fix this (codecov/uploader#426).

**Comment by nwu63** [comment]
Wow that was immediate. Do we wanna remove all the codecov tokens and stuff @sseraj

**Comment by sseraj** [comment]
> Wow that was immediate. Do we wanna remove all the codecov tokens and stuff @sseraj

I don't think there's any downside to keeping the tokens, especially because we need the variable group anyway. But I can remove them if you prefer.

**Pull request merged**
