### PR TITLE
Surface output for forces in lift and drag directions

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

This PR adds force coefficients per unit area projected in the lift and drag directions as surface output variables. Here is an example of the force in the drag direction for the MACH tutorial wing case:
force_in_drag_dir

It would be great if the reviewers could test this on their own cases.

## Expected time until merged

2-3 weeks

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

No tests, but I tried this on wing and full aircraft cases and the outputs made sense.

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [x] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Review by lamkina — DISMISSED** [review]

**Comment by marcomangano** [comment]
@sanjan98 and I will take a look soon. I believe it is time to make a new release for ADflow. There are no breaking changes here, right @sseraj ? Likely a patch release will be enough.

**Comment by sseraj** [comment]
That's right, there are no breaking changes in this PR. There have been some breaking changes since the last release though, like #330 and #359 to some extent.

**Comment by marcomangano** [comment]
Ok, so we should go for a minor release overall, given all these changes since the latest one. We can wait for #362 to be merged since it's minor and should be ready by the end of the week. If @lamkina is ok we can bump the minor (?) version here in the meantime?

**Comment by lamkina** [comment]
I think bumping the minor version here makes sense. #362 is just adding tests so I don't think it needs to be factored into the version bump.

**Review by marcomangano — APPROVED** [review]

**Review by lamkina — APPROVED** [review]

**Pull request merged**
