### PR TITLE
Updated displacement file handling

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
This PR fixes a minor logic in applying displacement files. Now, even if the point sets are up to date, if the displacements are nonzero they are still applied. I also made minor adjustments to the docstrings.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
N/A

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Review by Xiaosong2105 — APPROVED** [review]
Good catch. I have approved this PR.
I am thinking if every time we finish updating the point sets with displacement, we can reset the displacement to zeros.
Thus, the logic in the modified file can be simplified by only considering the current displacement is zero or not.

**Comment by nwu63** [comment]
That is a good point, I'm not sure how this will work with optimization. No idea if the displacements should be zeroed out, or applied every time.

**Comment by marcomangano** [comment]
That's a nice catch indeed! I am wondering how this affects the MDA/O results in terms of speed and accuracy

**Review by eirikurj — APPROVED** [review]
Looks good.
A note on usage, the `setDisplacements` function is rarely used and is not used in an aerostructural MDA e.g., `pyaerostructure`. This function is useful for example in an ASO when you want to deflect the aerodynamic shape depending on some structural loading obtained from a separate structural analysis. This would remain fixed throughout the optimization.
As for resetting it to `None` or zero, I dont see that being useful here because these displacements are intended to stay fixed throughout.
A minor comment, while its very likely that you will have a DVGeo object, it should probably be possible to set the displacements without requiring DVGeo object present. This could be done later though as I think 99% of the time you have a DVGeo object present.

**Pull request merged**
