### PR TITLE
The span function in the regtest is corrected

### PR DESCRIPTION
**Pull request by ArshSaja**
## Type of change

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by ArshSaja** [comment]
I know what's happening here. I will fix it..

**Comment by sseraj** [comment]
Could you also bump the version to 2.5.3? We haven't had a new release in a while, so I will make one after this is merged.

**Comment by marcomangano** [comment]
@ArshSaja good catch with the flattening error, please just fix the flake8 warnings, then this is good to go for me

**Comment by joanibal** [comment]
looks good

**Review by joanibal — APPROVED** [review]

**Comment by nwu63** [comment]
Yeah I thought I had code in `BaseRegTest` to convert singleton array to floats in order to reduce the number of lines in the JSON file, but I guess not. It would be a neat feature to have those two be inter-operable though.

**Review by marcomangano — APPROVED** [review]

**Review by nwu63 — APPROVED** [review]

**Comment by nwu63** [comment]
Sorry I forgot to bump the version, I just pushed to master @sseraj you can make a release now.

**Pull request merged**
